global_defaults:
  timeout: 3            # 连接超时时间(秒)
  reconnect_times: 0    # 0 表示无限次重连
  reconnect_interval: 2.0  # 重连间隔(秒)

connections:
  printer_left:
    ip: 192.168.0.23
    port: 6000
    enabled: false

  printer_center:
    ip: 192.168.0.24
    port: 6000
    enabled: true

  printer_right:
    ip: 192.168.0.26
    port: 6000
    enabled: false

