# 全局调试开关
debug: true

# 控制系统配置
control:
  # PID控制器参数
  pid:
    kp: 1         # 比例系数
    ki: 0        # 积分系数
    kd: 0.1       # 微分系数

# 运动控制参数
motion:
  # 速度控制
  velocity:
    # 速度限制
    limits:
      min: 0.05                    # 最小线速度
      walk_max: 0.28               # 步行模式最大速度
      work_max: 0.35               # 工作模式最大速度
      work_short: 0.2             # 短路径工作速度
      alignment: 0.05              # 对齐阶段速度
    
    # 距离参数
    distances:
      alignment: 0.08              # 对齐距离阈值
      deceleration: 0.15           # 开始减速的距离
      acceleration: 0.15           # 加速阶段距离
      walking: 0.05                # 步行距离
      lookahead: 0.3               # 前瞻距离
      waypoint_tolerance: 0.025    # 路径点容差
      mini_path: 0.3              # 最小路径距离
    
    # 速度调节参数
    tuning:
      acce_factor: 0.0005              # 加速因子
      speed_increment: 0.02            # 速度增量
      acceleration_factor: 6         # 加速sigmoid函数系数
      deceleration_factor: 3         # 减速sigmoid函数系数
      acceleration_sigmoid_center: 0.9 # 加速sigmoid函数中心点
      deceleration_sigmoid_center: 0.1 # 减速sigmoid函数中心点

  # 角速度控制参数
  angular:
    rotation:
      limits:
        max: 0.8                       # 最大角速度
        min: 0.15                      # 最小角速度
      tuning:
        factor: 1.2                    # 角速度调节因子
        angle_threshold: 0.5           # 角度阈值
        smooth_factor: 0.6             # 角速度平滑因子
    
    following:
      # Hampel滤波器配置
      hampel:
        window_size: 9             # 窗口大小
        k_threshold: 3             # 异常值检测阈值


# 传感器数据处理配置
sensors:
  # 位置数据处理配置
  position:
    filtering:
      alpha: 0.85                    # 低通滤波器平滑因子
      # Hampel滤波器配置
      hampel:
        window_size: 9               # 窗口大小
        k_threshold: 5             # 异常值检测阈值
      savgol:
        window_size: 7               # 窗口大小
        polynomial_order: 3          # 多项式阶数
    
    # 虚拟位置跟踪配置（超高精度直线跟随）
    virtual_tracking:
      enabled: false                  # 启用虚拟位置跟踪
      correction_gain: 0.15          # 全站仪数据修正增益 (0-1)
      max_correction: 0.003          # 最大单次修正量 (3mm超高精度)
      position_trust_threshold: 0.005 # 位置信任阈值 (5mm)
      
      # 地形自适应修正参数
      terrain_adaptive:
        smooth_gain: 0.25            # 平稳地形修正增益
        rough_gain: 0.08             # 不平整地形修正增益
        sudden_change_gain: 0.05     # 突变地形修正增益
      
      # 虚拟位置更新参数
      kinematics:
        max_velocity_trust: 0.5      # 最大可信速度 (m/s)
        angular_velocity_factor: 1.0 # 角速度影响因子
        
      # 调试和监控
      debug:
        enable_logging: false        # 启用虚拟跟踪日志
        log_frequency: 50           # 日志记录频率 (Hz)

  # IMU地形检测配置
  imu:
    terrain_adaptation:
      enabled: false                      # 启用地形自适应控制
      window_size: 1.5                   # 滑动窗口大小（秒）
      
      # 地形类型检测阈值
      thresholds:
        sudden_change_gradient: 0.002    # 突变地形检测阈值
        gentle_low_freq_energy: 0.06     # 平缓凹凸检测阈值
        frequent_zero_crossing: 2      # 频繁颠簸检测阈值
      

# 地形自适应控制参数
terrain_control:

  # 初始对齐参数（共用）
  alignment:
    cross_track_deadzone: 0       # 横向误差死区
    yaw_deadzone: 0                 # 航向误差死区
    max_angular_vel: 0.1                 # 最大角速度
    max_angular_accel: 0.03               # 最大角加速度
    suppression_factor: 1              # 抑制因子
    # 航向混合控制参数
    heading:
      current_heading_weight: 0        # 当前机器人航向权重 (0-1)
      target_heading_weight: 1         # 目标路径航向权重 (0-1)
    # 角速度滤波参数
    filtering:
      alpha: 0.95                            # 低通滤波器平滑因子（应用于角速度）
    # 二阶平滑器参数
    smoother:
      frequency: 15                   # 自然频率
      damping: 0.95                     # 阻尼比

  # 平稳地形参数（基准）
  smooth_terrain:
    cross_track_deadzone: 0         # 横向误差死区
    yaw_deadzone: 0.0                  # 航向误差死区
    max_angular_vel: 0.08                 # 最大角速度
    max_angular_accel: 0.03               # 最大角加速度
    suppression_factor: 1              # 抑制因子
    # 航向混合控制参数（平稳地形保持高精度）
    heading:
      current_heading_weight: 0        # 当前机器人航向权重 (基础值+补偿值)
      target_heading_weight: 1         # 目标路径航向权重 (基础值+补偿值)
    # 角速度滤波参数
    filtering:
      alpha: 0.95                     # 低通滤波器平滑因子（应用于角速度）
    # 二阶平滑器参数
    smoother:
      frequency: 15              # 自然频率
      damping: 0.95                # 阻尼比
  
  # 平缓凹凸地形参数
  gentle_undulation:
    cross_track_deadzone: 0.0012         # 横向误差死区
    yaw_deadzone: 0.005                  # 航向误差死区
    max_angular_vel: 0.5                 # 最大角速度
    max_angular_accel: 1.2               # 最大角加速度
    suppression_factor: 0.7              # 抑制因子
    # 航向混合控制参数（平缓凹凸适度增加惯性保持）
    heading:
      current_heading_weight: 0.1        # 当前机器人航向权重 (基础值+补偿值)
      target_heading_weight: 0.9         # 目标路径航向权重 (基础值+补偿值)
    # 角速度滤波参数（平缓地形增强平滑）
    filtering:
      alpha: 0.75                      # 低通滤波器平滑因子（应用于角速度）
    # 二阶平滑器参数（增加阻尼以适应地形变化）
    smoother:
      frequency: 12               # 自然频率
      damping: 1                 # 阻尼比
  
  # 频繁颠簸地形参数
  frequent_bumps:
    cross_track_deadzone: 0.002          # 横向误差死区
    yaw_deadzone: 0.008                  # 航向误差死区
    max_angular_vel: 0.4                 # 最大角速度
    max_angular_accel: 1               # 最大角加速度
    suppression_factor: 0.6              # 抑制因子
    # 航向混合控制参数（频繁颠簸增加航向稳定性）
    heading:
      current_heading_weight: 0.2        # 当前机器人航向权重 (基础值+补偿值)
      target_heading_weight: 0.8         # 目标路径航向权重 (基础值+补偿值)
    # 角速度滤波参数（频繁颠簸强化平滑）
    filtering:
      alpha: 0.7                       # 低通滤波器平滑因子（应用于角速度）
    # 二阶平滑器参数（降低频率增加阻尼以抑制颠簸）
    smoother:
      frequency: 10                # 自然频率
      damping: 1.1                  # 阻尼比
  
  # 突变地形参数（优先级最高）
  sudden_change:
    cross_track_deadzone: 0.003          # 横向误差死区
    yaw_deadzone: 0.01                   # 航向误差死区
    max_angular_vel: 0.3                 # 最大角速度
    max_angular_accel: 0.8               # 最大角加速度
    suppression_factor: 0.5              # 抑制因子
    # 航向混合控制参数（突变地形强化航向保持能力）
    heading:
      current_heading_weight: 0.3        # 当前机器人航向权重 (基础值+补偿值)
      target_heading_weight: 0.7         # 目标路径航向权重 (基础值+补偿值)
    # 角速度滤波参数（突变地形最强平滑）
    filtering:
      alpha: 0.65                        # 低通滤波器平滑因子（应用于角速度）
    # 二阶平滑器参数（最低频率最高阻尼以应对突变）
    smoother:
      frequency: 8         # 自然频率
      damping: 1.2           # 阻尼比

# 地形控制配置（立即切换模式）
terrain_control_mode:
  immediate_switch: true # 启用立即切换模式，一旦检测到地形变化立即切换状态

# 数据记录配置
data_logging:
  enabled: true
  base_path: "/home/daosn_robotics/zyq_ws/terrain_analysis_data/"
  frequency: 10                         # 记录频率（Hz）
  detailed_logging: true                  # 详细日志记录