# 全局调试开关
debug: true

# 控制系统配置
control:
  # PID控制器参数
  pid:
    kp: 1         # 比例系数
    ki: 0        # 积分系数
    kd: 0.1       # 微分系数

# 运动控制参数
motion:
  # 速度控制
  velocity:
    # 速度限制
    limits:
      min: 0.05                    # 最小线速度
      walk_max: 0.1               # 步行模式最大速度
      work_max: 0.1               # 工作模式最大速度
      work_short: 0.2             # 短路径工作速度
      alignment: 0.05              # 对齐阶段速度
    
    # 距离参数
    distances:
      alignment: 0.08              # 对齐距离阈值
      deceleration: 0.15           # 开始减速的距离
      acceleration: 0.15           # 加速阶段距离
      walking: 0.05                # 步行距离
      lookahead: 0.3               # 前瞻距离
      waypoint_tolerance: 0.025    # 路径点容差
      mini_path: 0.3              # 最小路径距离
    
    # 速度调节参数
    tuning:
      acce_factor: 0.0005              # 加速因子
      speed_increment: 0.02            # 速度增量
      acceleration_factor: 6         # 加速sigmoid函数系数
      deceleration_factor: 3         # 减速sigmoid函数系数
      acceleration_sigmoid_center: 0.9 # 加速sigmoid函数中心点
      deceleration_sigmoid_center: 0.1 # 减速sigmoid函数中心点

  # 角速度控制参数
  angular:
    rotation:
      limits:
        max: 0.8                       # 最大角速度
        min: 0.15                      # 最小角速度
      tuning:
        factor: 1.2                    # 角速度调节因子
        angle_threshold: 0.5           # 角度阈值
        smooth_factor: 0.6             # 角速度平滑因子
    
    following:
      # Hampel滤波器配置
      hampel:
        window_size: 9             # 窗口大小
        k_threshold: 3             # 异常值检测阈值


# 传感器数据处理配置
sensors:
  # 位置数据处理配置
  position:
    filtering:
      alpha: 0.85                    # 低通滤波器平滑因子
      # Hampel滤波器配置
      hampel:
        window_size: 9               # 窗口大小
        k_threshold: 5             # 异常值检测阈值
      savgol:
        window_size: 7               # 窗口大小
        polynomial_order: 3          # 多项式阶数
    

# 地形自适应控制参数
terrain_control:

  # 初始对齐参数（共用）
  alignment:
    cross_track_deadzone: 0       # 横向误差死区
    yaw_deadzone: 0                 # 航向误差死区
    max_angular_vel: 0.1                 # 最大角速度
    max_angular_accel: 0.03               # 最大角加速度
    suppression_factor: 1              # 抑制因子
    # 航向混合控制参数
    heading:
      current_heading_weight: 0        # 当前机器人航向权重 (0-1)
      target_heading_weight: 1         # 目标路径航向权重 (0-1)
    # 角速度滤波参数
    filtering:
      alpha: 0.95                            # 低通滤波器平滑因子（应用于角速度）
    # 二阶平滑器参数
    smoother:
      frequency: 15                   # 自然频率
      damping: 0.95                     # 阻尼比

  # 平稳地形参数（基准）
  smooth_terrain:
    cross_track_deadzone: 0         # 横向误差死区
    yaw_deadzone: 0.0                  # 航向误差死区
    max_angular_vel: 0.08                 # 最大角速度
    max_angular_accel: 0.03               # 最大角加速度
    suppression_factor: 1              # 抑制因子
    # 航向混合控制参数（平稳地形保持高精度）
    heading:
      current_heading_weight: 0        # 当前机器人航向权重 (基础值+补偿值)
      target_heading_weight: 1         # 目标路径航向权重 (基础值+补偿值)
    # 角速度滤波参数
    filtering:
      alpha: 0.95                     # 低通滤波器平滑因子（应用于角速度）
    # 二阶平滑器参数
    smoother:
      frequency: 15              # 自然频率
      damping: 0.95                # 阻尼比
  