#----- 位置和方向容忍度 -----
goal_dist_tol: 0.02    # 目标位置容忍度（单位：米，2厘米）
rotate_tol: 0.035      # 目标朝向角度容忍度（单位：弧度，约2度）

#----- 前瞻参数 -----
lookahead_time: 0.15    # 前瞻时间（单位：秒）
min_lookahead_dist: 0.18  # 最小前瞻距离（单位：米）
max_lookahead_dist: 0.18    # 最大前瞻距离（单位：米）

#----- 线速度参数 -----
max_v: 0.3             # 最大线速度（单位：米/秒）
min_v: 0.06            # 最小线速度（单位：米/秒）
max_v_inc: 0.06        # 最大线速度增量（单位：米/秒²）
linear_speed: 0.06      # 基准线速度（单位：米/秒）

#----- 角速度参数 -----
max_w: 1.0             # 最大角速度（单位：弧度/秒）
min_w: 0.03            # 最小角速度（单位：弧度/秒）
max_w_inc: 0.06        # 最大角速度增量（单位：弧度/秒²）

#----- 路径跟踪参数 -----
regulated_min_radius: 0.5    # 应用曲率约束的最小半径阈值（单位：米）
approach_dist: 0.05           # 接近目标的距离阈值（单位：米）
approach_min_v: 0.07          # 接近目标时的最小速度（单位：米/秒）

x_offset: 0.0
y_offset: 0.0

radius_log_file_path: '/home/daosn_robotics/zyq_ws/rpp_circle.csv'

radius_offset: 0.0
lowpass_angular_vel_filter_gain: 0.9
angular_vel_history_size: 1
smoothing_type: 'lowpass'  # 'lowpass' | 'movingAverage' | 'none'

# 二阶平滑器参数
smoother_freq: 15.0      # 自然频率 (Hz)，控制响应速度
smoother_damping: 0.9   # 阻尼比，控制震荡程度

low_speed_mode: True
collect_positions_for_circle: False
enable_grid_map: True
pos_use_biquad_cascade: True
pos_use_biquad_cascade_filter: False
pos_cutoff_freq: 1.5              # 位置数据截止频率
pos_sample_rate: 18.0             # 采样率
pos_output_limit: 0.3            # 位置范围限制
pos_rate_limit: 0.3               # 位置变化率限制 (m/s)

# 四阶低通滤波参数
angle_use_biquad_cascade: True
angle_use_biquad_cascade_filter: True
angle_use_offset_limit: True
angle_output_offset: 0.1
angle_cutoff_freq: 1.5              # 位置数据截止频率
angle_sample_rate: 18.0             # 采样率
angle_output_limit_rate: 1.05            # 输出的最大速度比率
angle_rate_limit: 0.03               # 变化率限制 

start_deviation_factor: 0.5
end_deviation_factor: 0.5
deviation_rate: 0.1